name: 🚀 Deploy Odoo to Azure

on:
  push:
    branches:
      - main  # Deployment berjalan otomatis saat ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 📂 Copy Files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "."
          target: "~/sadaya-deploy"

      - name: 🐳 Execute Docker Compose via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/sadaya-deploy
            # Mematikan container lama dan menjalankan yang baru beserta perubahannya
            docker compose down
            docker compose up -d --build